### ISSUE TITLE
Simple objects

### ISSUE THREAD

**Issue by mikamyrseth** [mikamyrseth/Flounder#1]
As a user I want to use the user interface to specify object position, weight, and hitbox such that I can create a simulation world before running the simulation

- [x] Find input file format solution
- [x] Create input file parser // Mika and Leonard
- [x] Create class for simulation // Leonard
- [x] Create struct for object in simulation // Solveig and Leonard
- [x] Functionality to parse input file into simulation // Mika and Leonard
- [x] Unit testing // Leonard

**Comment by mikamyrseth** [comment]
- [ ]

**Comment by mikamyrseth** [comment]
Json Vedtatt!

**Comment by mikamyrseth** [comment]
Supert.

**Comment by le0-0** [comment]
Unit tests for parsing of the different components

**Comment by le0-0** [comment]
Unit tests has been added
